name: Build and Upload Package on Release

on:
  release:
    types:
      - created

jobs:
  build_and_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref_name }}

#    - name: Set up Miniconda
#      uses: conda-incubator/setup-miniconda@v2
#      with:
#        miniforge-variant: Mambaforge
#        miniforge-version: latest
#        activate-environment: build_env
#        auto-activate-base: false
#        mamba-version: '*'
#
#    - name: Install dependencies
#      shell: bash -l {0}
#      run: |
#        conda install conda-build anaconda-client

#    - name: Run Shell Script
#      shell: bash -l {0}
#      env:
#        ANACONDA_USERNAME: ${{ secrets.ANACONDA_USERNAME }}
#        ANACONDA_PASSWORD: ${{ secrets.ANACONDA_PASSWORD }}
#      run: |
#        chmod +x ./build_and_upload.sh
#        RELEASE_VERSION=${{ github.event.release.tag_name }}
#        ./build_and_upload.sh $RELEASE_VERSION
    - name: Create file
      run: echo 'some stuff' > ./your_file.txt

    - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
      run: |
        git config --global user.name "Git actions"
        git config --global user.email "username@users.noreply.github.com"
        git add ./your_file.txt
        git commit -a -m "Commit new version"
        git push origin HEAD:develop --force
